# gradle/libs.versions.toml
[versions]
spring-boot = "3.5.5"
spring-cloud = "2025.0.0"
dependency-management = "1.1.7"
axon = "4.12.1"
springdoc = "2.8.13"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
axon-bom = { module = "org.axonframework:axon-bom", version.ref = "axon" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "spring-boot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
